---
- name: disable ACT LED
  lineinfile:
    path: /boot/config.txt
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
    - { regex: dtparam=act_led_trigger=, line: dtparam=act_led_trigger=none }
    - { regex: dtparam=act_led_activelow=, line: dtparam=act_led_activelow=on }
