---
- hosts: all:!laptops
  remote_user: pi
  roles:
    - { role: prelim-setup }
  tags: prelim-setup

- hosts: all
  roles:
    - { role: common }
  tags: common

- hosts: pies
  roles:
    - { role: disable-leds, tags: [disable-leds] }
  tags: optimize

- hosts: pies
  roles:
    - bluetooth
  tags: bluetooth

- hosts: radio
  roles:
    - radio
    - { role: radio-control-backend, tags: [rcon-back, rcon] }
  tags: radio

- hosts: headless_pies
  roles:
    - { role: optimize-headless-pies }
  tags: optimize

- hosts: dmz
  roles:
    - { role: dmz-ssh, tags: [dmz-ssh, ssh-dmz, ssh] }
    - { role: docker, tags: [docker] }
    - { role: ingress, tags: [ingress] }
    - { role: tor, tags: [tor] }
    - { role: radio-control-frontend, tags: [rcon-front, rcon, radio] }
  tags: dmz

- hosts: dns_servers
  roles:
    - dns-server
  tags: dns, dns-server

# TODO write radio role
# TODO deploy radio backend
# TODO deploy radio front-end
# TODO openvpn O_O
# TODO setup fund prices tracking
# TODO setup transmission-gtk to run in docker container, expose in
# traefik
# - hosts: climate
#   tasks:
#     - name: enable i2c part 1
# make sure line `dtparam=i2c_arm=on` is in `/boot/config.txt`
# make sure line `i2c-dev` is at bottom of `/etc/modules`
# install i2c-tools and python-smbus
# install with pip adafruit-circuitpython-am2320
# if device is connected, run `i2cdetect -y 1` twice and expect some
# non-hyphen output (only if you feel like it)
# install binary/script in /usr/local/bin with right rights and owner
# create logs dir
# setup line in crontab (file?)
