---
- name: disable SAP as it gives an error message
  lineinfile:
    insertafter: [Service]
    regexp: ^ExecStart
    line: ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap
    path: /etc/systemd/system/bluetooth.target.wants/bluetooth.service
  register: disable_sap

- name: restart bluetooth service
  systemd:
    daemon-reload: yes
    name: bluetooth
    state: restarted
  when: disable_sap.changed

- name: install pulse-audio and deps
  apt:
    name: "{{ item }}"
  with_items:
    - pulseaudio
    - pavucontrol
    - pulseaudio-module-bluetooth
  register: install_pa

- name: reboot
  shell: shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  when: install_pa.changed

- name: wait for reboot
  local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=90 timeout=180
  when: install_pa.changed

- name: enable controllers by default
  lineinfile:
    regexp: AutoEnable
    insertafter: [Policy]
    line: AutoEnable=true
    path: /etc/bluetooth/main.conf
  # TODO look into ReconnectUUIDs in that section!
