---
- name: store audio pro speaker address in environment
  lineinfile:
    dest: /etc/environment
    line: t5=40:EF:4C:1D:37:F0

- name: install necessary packages
  apt:
    name:
    - pulseaudio
    - pulseaudio-module-bluetooth
    - pavucontrol
    - bluez-firmware

# not strictly necessary, just convenience
- name: make sure users {{ users }} are in bluetooth group
  user:
    groups: bluetooth
    append: yes
    name: "{{ item.name }}"
  loop: "{{ users }}"
  notify: reboot
  tags: bluetooth-group

- name: put pulse audio service unit file in place
  copy:
    src: files/pulseaudio.service
    dest: /etc/systemd/system/pulseaudio.service
  register: pa_service_file
  notify:
    - restart pulseaudio

- name: make sure we use a speaker once we connect
  lineinfile:
    path: /etc/pulse/default.pa
    regex: "#?load-module module-switch-on-connect"
    line: load-module module-switch-on-connect
  notify:
    - restart pulseaudio

- name: enable and start pulseaudio service
  systemd:
    name: pulseaudio
    enabled: true
    daemon_reload: "{{ pa_service_file.changed }}"
    state: started
  notify:
    - restart bluetooth
