---
- name: Install keyring
  pip:
    name: keyrings.alt

- name: Install bonfire
  pip:
    name: git+https://github.com/blue-yonder/bonfire.git@d0af9ca10394f366cfa3c60f0741f1f0918011c2#egg=bonfire

- name: Paste bonfire config
  copy:
    src: "bonfire.cfg"
    dest: "/home/{{ user | default('valkra') }}/.bonfire.cfg"
    mode: 0644
    owner: "{{ user | default('valkra') }}"
    group: "{{ user | default('valkra') }}"
  tags:
    - valkra
