---
- name: Install basic toolsgit
  apt:
    name:
    - htop
    - git
    - fish
    - tree
    - lsof
    - screen
    - jq
    - python3
    - python3-pip
    - wget
    - vim

- name: Paste vals .vimrc
  copy:
    src: "val-ubuntu-vimrc"
    dest: "/home/{{ user | default('val') }}/.vimrc"
    mode: 0644
    owner: "{{ user | default('val') }}"
    group: "{{ user | default('val') }}"
  tags:
    - val
  register: paste_vimrc

- name: Paste vals .screenrc
  copy:
    src: "val-screenrc"
    dest: "/home/{{ item.name }}/.screenrc"
    mode: 0644
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items:
    - { name: val }
    - { name: naz }
  tags:
    - screen

- user:
    name: val
    groups: adm,sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /usr/bin/fish
    password: $6$9/wKN0wpSk.TQi$syKdFMSR6OqSy8R31.X/k8.JaBR22xUKa/92.uthEIkGye3n.h2R2A0Lgp16aPUCOvh0e3.uKiZCpAO8ATRdd0
    update_password: on_create
  tags:
    - users
