---
- name: Install basic toolsgit
  apt:
    name:
    - htop
    - git
    - fish
    - tree
    - lsof
    - screen
    - jq
    - python3
    - python3-pip
    - wget
    - vim

- name: Install omf
  become: item.name
  shell:
    executable: /usr/bin/fish
    cmd: |
      curl -Ls https://get.oh-my.fish -o /tmp/omf.fish && \
      fish /tmp/omf.fish --noninteractive
    warn: false
  register: omf_install
  changed_when: "'Existing installation detected' not in
    omf_install.stdout"
  failed_when: omf_install.rc != 0 and 'Existing installation detected' not in
    omf_install.stdout
  loop: "{{ users }}"

- name: Choose theme
  become: item.name
  shell:
    executable: /usr/bin/fish
    cmd: omf install red-snapper
  changed_when: false
  loop: "{{ users }}"

- name: Paste vals .vimrc
  copy:
    src: "val-ubuntu-vimrc"
    dest: "/home/{{ user | default('val') }}/.vimrc"
    mode: 0644
    owner: "{{ user | default('val') }}"
    group: "{{ user | default('val') }}"
  tags:
    - val
  register: paste_vimrc

- name: Paste vals .screenrc
  copy:
    src: "val-screenrc"
    dest: "/home/{{ item.name }}/.screenrc"
    mode: 0644
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items:
    - { name: val }
    - { name: naz }
  tags:
    - screen

      # TODO - name: add /etc to git control, and do first commit
