---
- name: Install basic tools
  apt:
    name:
    - htop
    - git
    - fish
    - tree
    - lsof
    - screen
    - jq
    - python3
    - python3-pip
    - wget
    - vim
  tags: basic-tools

- name: Install omf
  become: item.name
  shell:
    executable: /usr/bin/fish
    cmd: |
      curl -Ls https://get.oh-my.fish -o /tmp/omf.fish && \
      fish /tmp/omf.fish --noninteractive
    warn: false
  register: omf_install
  changed_when: "'Existing installation detected' not in
    omf_install.stdout"
  failed_when: omf_install.rc != 0 and 'Existing installation detected' not in
    omf_install.stdout
  loop: "{{ users }}"
  tags: omf

- name: Choose theme
  become: item.name
  shell:
    executable: /usr/bin/fish
    cmd: omf install red-snapper
  changed_when: false
  loop: "{{ users }}"
  tags: omf

- name: Paste vals .vimrc
  copy:
    src: "val-ubuntu-vimrc"
    dest: "/home/{{ user | default('val') }}/.vimrc"
    mode: 0644
    owner: "{{ user | default('val') }}"
    group: "{{ user | default('val') }}"
  when: "'pies' in group_names"
  tags: vimrc

  # TODO need to install vundle or whatever plugin manager we use for our vimrc
  # to work!

- name: Paste vals .screenrc
  copy:
    src: "val-screenrc"
    dest: "/home/{{ item.name }}/.screenrc"
    mode: 0644
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"
  tags: screenrc

- name: Set time zone
  lineinfile:
    dest: /etc/environment
    line: TZ=Europe/Oslo
  tags: timezone
