---
- name: Install basic tools
  apt:
    name:
    - htop
    - git
    - fish
    - tree
    - lsof
    - screen
    - jq
    - python3
    - python3-pip
    - wget
    - nmap
    - vim
    - silversearcher-ag
  tags: basic-tools

- name: Link python to python3
  file:
    state: link
    src: /usr/bin/python3
    path: /usr/bin/python

- name: Remove all traces of python2
  apt:
    name:
    - python2
    - python2-minimal
    - python2.7
    - python2.7-minimal
    - libpython2-stdlib:armhf
    - libpython2.7-minimal:armhf
    - libpython2.7-stdlib:armhf
    state: absent

- name: Install omf
  become: item.name
  shell:
    executable: /usr/bin/fish
    cmd: |
      curl -Ls https://get.oh-my.fish -o /tmp/omf.fish && \
      fish /tmp/omf.fish --noninteractive
    warn: false
  register: omf_install
  changed_when: "'Existing installation detected' not in
    omf_install.stdout"
  failed_when: omf_install.rc != 0 and 'Existing installation detected' not in
    omf_install.stdout
  loop: "{{ users }}"
  tags: omf

- name: Choose theme
  become: item.name
  shell:
    executable: /usr/bin/fish
    cmd: omf install red-snapper
  changed_when: false
  loop: "{{ users }}"
  tags: omf

- name: Paste vals .vimrc
  copy:
    src: "val-ubuntu-vimrc"
    dest: "/home/{{ user | default('val') }}/.vimrc"
    mode: 0644
    owner: "{{ user | default('val') }}"
    group: "{{ user | default('val') }}"
  when: "'pies' in group_names"
  tags: vimrc

  # TODO need to install vundle or whatever plugin manager we use for our vimrc
  # to work!
  #
- name: configure system vim settings
  blockinfile:
    dest: /etc/vim/vimrc
    marker: '" ANSIBLE NO TEMP NO MOUSE {mark}'
    block: |
      set noswapfile
      set mouse-=a
  tags: vimrc

- name: Paste vals .screenrc
  copy:
    src: "val-screenrc"
    dest: "/home/{{ item.name }}/.screenrc"
    mode: 0644
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"
  tags: screenrc

- name: Set time zone
  lineinfile:
    dest: /etc/environment
    line: TZ=Europe/Oslo
  tags: timezone

- name: Install pip requirements
  shell:
    cmd: python3 -m pip install setuptools virtualenv
  tags: pip
