- name: Install vim
  apt:
    name: vim

- name: Paste vals .vimrc
  copy:
    src: "val-ubuntu-vimrc"
    dest: "/home/{{ user | default('val') }}/.vimrc"
    mode: 0644
    owner: "{{ user | default('val') }}"
    group: "{{ user | default('val') }}"
  tags:
    - val
  register: paste_vimrc

# TODO the above is not idempotent - either fix, or wait until old ubuntus are
# retired

- name: Ensure .vim dir exists
  file:
    path: "/home/{{ user | default('val') }}/.vim"
    mode: 0755
    owner: "{{ user | default('val') }}"
    group: "{{ user | default('val') }}"
    state: directory

- name: Download vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/home/{{ user | default('val') }}/.vim/bundle/Vundle.vim"
  register: vundle_download

- name: Change file permissions
  file:
    path: "/hyome/{{ user | default('val') }}/.vim/bundle"
    state: directory
    recurse: yes
    owner: "{{ user | default('val') }}"
    group: "{{ user | default('val') }}"

  # TODO fix the changed when thing - find out why cmd always has rc 1
  # TODO make it work with become_user ?!? O_o
  #- name: Install vim plugins
  #  become_user: "{{ user | default('val') }}"
  #  shell: vim -E -c "source ~/.vimrc" -c PluginInstall -c qa
  #  #when: paste_vimrc.changed or vundle_download.changed
  #  register: install_vim_plugins
  #  failed_when: false

  #- name: Install dependencies for YCM
  #  apt:
  #    name: "{{ item }}"
  #    update_cache: yes
  #  with_items:
  #    - cmake
  #    - build-essential
  #    - python3
  #    - python-dev
  #    - python3-dev
  #
  #- name: Download Ycm
  #  become_user: "{{ user | default('val') }}"
  #  git:
  #    repo: "https://github.com/Valloric/YouCompleteMe.git"
  #    dest: "/home/{{ user | default('val') }}/.vim/bundle/YouCompleteMe"
  #    recursive: yes
  #  register: ycm_download
  #
  #- debug:
  #    var: ycm_download
  #
  #- name: Install or compile ycm
  #  become_user: "{{ user | default('val') }}"
  #  shell: python3 /home/{{ user | default('val') }}/.vim/bundle/YouCompleteMe/install.py
  #  register: ycm_compile
  #
  #- debug:
  #    var: ycm_compile
  #
  #
