---
- name: install prerequisites
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: setup repo
  block:
    - name: add signing key
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg
    - name: get architecture
      shell:
        cmd: dpkg --print-architecture
      register: arch
      changed_when: no
    - name: record linux repository in sources
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        create: yes
        line: >-
          deb [arch={{ arch.stdout }}]
          https://download.docker.com/linux/{{ ansible_lsb.id | lower }}
          {{ ansible_lsb.codename }} stable

- name: install docker
  apt:
    install_recommends: no
    update_cache: yes
    name:
    - docker-ce
    - cgroupfs-mount

- name: make sure docker service is enabled and started
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes
    state: started

- name: setup python docker sdk for using ansible docker module
  pip:
    name: docker
