---
- name: install prerequisites
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: setup repo
  block:
    - name: make sure keys directory exists
      file:
        path: "{{ keys_dir }}"
        state: directory
    - name: add signing key
      shell:
        cmd: >
          curl -fsSl https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg |
          gpg --dearmor -o {{ keys_dir }}/docker.gpg
        creates: "{{ keys_dir }}/docker.gpg"
        executable: /bin/bash
    - name: get architecture
      shell:
        cmd: dpkg --print-architecture
      register: arch
      changed_when: no
    - name: record linux repository in sources
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        create: yes
        line: >-
          deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/{{ ansible_lsb.id | lower }}
          {{ ansible_lsb.codename }} stable

- name: install docker
  apt:
    install_recommends: no
    update_cache: yes
    name:
    - docker-ce
    - cgroupfs-mount

- name: make sure docker service is enabled and started
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes
    state: started

- name: setup python docker sdk for using ansible docker module
  pip:
    name: docker
