- name: do the prelim setup
  block:
  - name: install fish as that's our favourite shell
    apt:
      name: fish
      update_cache: yes

  - name: setup val user
    user:
      name: val
      groups: adm,sudo
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      shell: /usr/bin/fish
      password: "$6$DGNSSPV0Vq$JHBYIH03r67ySoXjDIdLlasLIlwBem.dhhdZmlFavGABI5Y\
                 xB3ABd2v4SjVvwuM9T/hMhfoKuhufkF2sDqNyO/"

  - name: copy authorized_keys file
    copy:
      dest: /home/val/.ssh/authorized_keys
      owner: val
      group: val
      mode: 0600
      src: files/val_authorized_keys

  - pause:
      prompt: |
        pls try sshing to {{ansible_hostname}} using your key - abort execution
        if this does not work as we're about to disable password authentication
        for ssh

  - name: disable password ssh access
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^#?PasswordAuthentication
      line: PasswordAuthentication no

  - name:
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: ensure USA USA locale exists
    community.general.locale_gen:
      name: en_US.UTF-8
      state: present

  - name: make sure default password-less user is not configured
    file:
      path: /etc/sudoers.d/010_pi-nopasswd
      state: absent

  when: "'prelim-setup' in ansible_run_tags"
